# Question1

In [3]:
list=[]
for x in range(2000,3201):
    if x%5!=0:
        if x%7==0:
            list.append(x)
list    

[2002,
 2009,
 2016,
 2023,
 2037,
 2044,
 2051,
 2058,
 2072,
 2079,
 2086,
 2093,
 2107,
 2114,
 2121,
 2128,
 2142,
 2149,
 2156,
 2163,
 2177,
 2184,
 2191,
 2198,
 2212,
 2219,
 2226,
 2233,
 2247,
 2254,
 2261,
 2268,
 2282,
 2289,
 2296,
 2303,
 2317,
 2324,
 2331,
 2338,
 2352,
 2359,
 2366,
 2373,
 2387,
 2394,
 2401,
 2408,
 2422,
 2429,
 2436,
 2443,
 2457,
 2464,
 2471,
 2478,
 2492,
 2499,
 2506,
 2513,
 2527,
 2534,
 2541,
 2548,
 2562,
 2569,
 2576,
 2583,
 2597,
 2604,
 2611,
 2618,
 2632,
 2639,
 2646,
 2653,
 2667,
 2674,
 2681,
 2688,
 2702,
 2709,
 2716,
 2723,
 2737,
 2744,
 2751,
 2758,
 2772,
 2779,
 2786,
 2793,
 2807,
 2814,
 2821,
 2828,
 2842,
 2849,
 2856,
 2863,
 2877,
 2884,
 2891,
 2898,
 2912,
 2919,
 2926,
 2933,
 2947,
 2954,
 2961,
 2968,
 2982,
 2989,
 2996,
 3003,
 3017,
 3024,
 3031,
 3038,
 3052,
 3059,
 3066,
 3073,
 3087,
 3094,
 3101,
 3108,
 3122,
 3129,
 3136,
 3143,
 3157,
 3164,
 3171,
 3178,
 3192,
 3199]

# Question2

In [2]:
x=int(input('select a number: '))
f=1
if x==0:
    print(f)
else:
    for i in range(x):
        f=f*(x-i)
    print(f)

select a number: 5
120


# Question3

In [1]:
x=int(input('select a number: '))
dictionary={}
for i in range (1,x+1):
    dictionary.update({i:i*i})
print(dictionary)

select a number: 5
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


# Question4

In [4]:
string=input('write a string: ')
new_string=''
ok = False

while not ok:
    x = int(input('select a number: '))
    ok= 0<=x<len(string)


for i in range (0,len(string)):
    if i!=x:
        new_string+=string[i]
 
print(new_string)


write a string: hotels
select a number: 10
select a number: 6
select a number: 3
hotls


# Question5

In [5]:
import numpy as np
array=np.array([[0,1],[2,3],[4,5]])
print(array)
array=array.tolist()
print(array)

[[0 1]
 [2 3]
 [4 5]]
[[0, 1], [2, 3], [4, 5]]


# Question6

In [9]:
import numpy as np
array1=np.random.randint(0,11,size=(1,3))
array2=np.random.randint(0,11,size=(1,3))
print(array1,array2)
print(np.cov(array1,array2))

[[2 5 8]] [[3 7 8]]
[[9.  7.5]
 [7.5 7. ]]


# Question7

In [10]:
import math
C=50
H=30

def inter():
    x=int(input('select a number: '))
    while x<0:
        x=int(input('select a number: '))
    return x

D=str(inter())+','+str(inter())+','+str(inter())


d1=int(D[0:D.find(',')])
d2=int(D[(D.find(',')+1):D.find(',',D.find(',')+1,len(D))])
d3=int(D[D.find(',',D.find(',')+1,len(D))+1:len(D)])

Q1=round(math.sqrt((2*C*d1)/H))
Q2=round(math.sqrt((2*C*d2)/H))
Q3=round(math.sqrt((2*C*d3)/H))

Q=str(Q1)+','+str(Q2)+','+str(Q3)
print(D)
print(Q)

select a number: 1000
select a number: 1500
select a number: 1800
1000,1500,1800
58,71,77
